### ISSUE TITLE
As a guest, I can log in to my account

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#10]
As a guest user,
When I visit the root page and select “log in”
When I fill in my log-in information
I am able to log-in to my account and 
I am redirected to my dashboard and
I am able to view all of my folders and files and those shared with me

**Comment by cmacaulay** [comment]
- As a user, when i click on "log-in"
-- I am redirected to a log in page
-- I can log-in using twillio's authentication process

**Comment by s-espinosa** [comment]
@cmacaulay Let's go through this during the checkin. I want to see the Twilio functionality, but didn't put in a real number.
