### ISSUE TITLE
debug file download

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#123]
- adding `require "zip"` to the application controller
- changing line 13 of `zip_generator.rb` to ` ::Zip::File.open(temp_file.path, ::Zip::File::CREATE) do |zipfile|`
- this makes it so that:
-- I can download an image successfully
-- I can download a nested folder from its show page with it's contents * also downloads parent folders
-- I can download the root folder from the folder show page
-- I can download the root folder from /home but cannot open the file

**Comment by AliSchlereth** [comment]
Check!
