### ISSUE TITLE
As a registered user, I can update my account information

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#19]
As a registered user,
when I am logged in to my account
when I visit my /home page 
when I select "update account" 
I am redirected to an edit account information page
When I fill out the new information
I am redirected to my profile page
And it contains the updated information

**Comment by s-espinosa** [comment]
@cmacaulay Doesn't currently redirect to my profile page. Does that exist? If not, let's discuss best redirect here.
