### ISSUE TITLE
As a registered user, I can view a single file that I own

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#22]
As a registered user, 
When I navigate to a folder 
When I select a single file
Then I am redirected to that file’s page 
And am able to see that file’s: name, size, extension
And can view and make a comment on that file
And can delete that file

**Comment by s-espinosa** [comment]
@cmacaulay Doesn't look like there's delete functionality on this view yet? Let me know if I missed it.

**Comment by cmacaulay** [comment]
@s-espinosa working on it - there's a PR open for delete on the index, still need to add it to the show page though! I will make another waffle card.
