### ISSUE TITLE
As a registered user, I can view the contents of a private folder that I own

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#23]
As a registered user,
When I visit my /home page
When I select a single private folder
I am redirected to that folder’s page
Where I can see links to all files within the folder
And any nested folders
And can delete the folder, or any of its (immediate) contents from that page

**Comment by s-espinosa** [comment]
@cmacaulay Similarly, no delete functionality here that I can see. Otherwise, looks good!

**Comment by cmacaulay** [comment]
@s-espinosa this is currently in process! Good catch.
