### ISSUE TITLE
As a registered user, I can comment on a private file I own

### ISSUE THREAD

**Issue by alfosco** [cmacaulay/folio-share#81]
As a registered user,
When I navigate to a file show page
I am able to make a comment on that file

**Comment by alfosco** [comment]
[WIP] When navigating to a file's show page, typing in a comment, and clicking submit, the comment does not show up on the page. While trying to debug it looks like the comment is saving. I have no clue why this isn't working.

**Comment by s-espinosa** [comment]
:tada:
